### PR TITLE
diable prflx over relay for firefox

### LINKED ISSUE #1216: "Could not connect PeerConnection after timeout" with Firefox and TURN
I've seen several similar issues, but my case somewhat strange, so could you please direct me what i should check?

In most cases when i trying to connect to livekit i get "Could not connect PeerConnection after timeout" error. But sometimes, i just randomly staring to work, and after that in continues to work for extended period of time. I mainly use FoundryVTT js client, but the https://example.livekit.io/ gives me exactly the same results. 

But! If i try to connect using https://livekit.io/connection-test, it always fully passes.
```
Connecting to signal connection via WebSocket
Connected to server, version 1.3.1.
Establishing WebRTC connection
SKIPPED: Can connect via TURN
WARNING: No TURN servers configured.
Can publish audio
published 140 audio packets
Can publish video
published 967 video packets
Resuming connection after interruption
PASS
```

The problem persist even with fully stopped firewall.  
Here's the server log [livekit_log.txt](https://github.com/livekit/livekit/files/10174540/livekit_log.txt)

What i am doing wrong?

**Clients**
Different with different results.

**Server**
- Version: [1.3.1]
- Environment: VPS, CentOS 8, without docker
- Using nginx as a reverse proxy

Nginx Configuration:
```nginx
server {
   server_name some.real.address.onine;

   proxy_read_timeout 300;
   proxy_connect_timeout 300;
   proxy_send_timeout 300;

   location / {
        proxy_set_header        Host $host;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto $scheme;

        proxy_pass http://127.0.0.1:7880;

        proxy_http_version      1.1;
        proxy_set_header        Upgrade $http_upgrade;
        proxy_set_header        Connection "Upgrade";
   }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/some.real.address.onine/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/some.real.address.onine/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}
```

Livekit Configuration:
```yaml
port: 7880
log_level: debug
rtc:
  tcp_port: 7881
  udp_port: 7882
  #port_range_start: 50000
  #port_range_end: 60000
  use_external_ip: true
redis:
  address: localhost:6379
keys:
  # key value pairs
  ***:**************
```
i tried both port ranges and single udp port. both with use_external_ip and without with no visible changes.

### PR DESCRIPTION
**Pull request by cnderrauber**
fix #1216 

There are two cases cause firefox can’t connect to sfu’s private address through turn relay, all are related to prflx over relay candidate.
1. Not force relay on client, but block the server’s udp port for client.
a. when ff received a stun-response that xor-mapped-addr not recognized, it will create a prflx over the relay candidate, but set the base to local addr (not relay addr)
b. when server nominates the prflx addr in a stun request, ff set the local addr of the request to relay addr (it received msg from the relay addr), then the prflx will not pass the response check (it’s addr not equal to the request’s addr), so the nominate failed.
2. force relay on client
a. ff will not create prflx base relay candidate in 1.a, and drop the response
b. when server nominates the prflx candidate, ff don’t have the candidate then failed.

This pr is a workaround in server-side will only expose public address to disable prflx over relay for firefox client.

### CODE REVIEW

File: pkg/rtc/clientinfo.go [hunk 1]
```diff
@@ -12,7 +12,11 @@ type ClientInfo struct {
 }
 
 func (c ClientInfo) SupportsAudioRED() bool {
-	return c.ClientInfo != nil && c.ClientInfo.Browser != "firefox" && c.ClientInfo.Browser != "safari"
+	return c.ClientInfo != nil && !strings.EqualFold(c.ClientInfo.Browser, "firefox") && !strings.EqualFold(c.ClientInfo.Browser, "safari")
```
Comment (davidzhao) [inline pkg/rtc/clientinfo.go:15]: can we add. IsFirefox function to encapsulate the check? same for Safari

**Review by davidzhao — APPROVED** [review]
