### PR TITLE
Persist participant before firing webhook

### LINKED ISSUE #1339: TrackPublished webhook is firing prior to DB update
**Describe the bug**
When a server integration receives TrackPublished webhook, the underlying Participant record has not been persisted yet.

This leads to ListParticipant API to not return the just published track.

**Server**
- Version: 1.3.3

### PR DESCRIPTION
**Pull request by davidzhao**
Fixes #1339

### CODE REVIEW

**Review by paulwe — APPROVED** [review]
lgtm

File: pkg/rtc/participant.go [hunk 1]
```diff
@@ -534,9 +534,13 @@ func (p *ParticipantImpl) handleMigrateMutedTrack() {
 	p.mutedTrackNotFired = append(p.mutedTrackNotFired, addedTracks...)
 	p.pendingTracksLock.Unlock()
 
-	for _, t := range addedTracks {
-		p.handleTrackPublished(t)
-	}
+	// launch callbacks in goroutine since they could block
+	// callbacks handle webhooks as well as db persistence
```
Comment (boks1971) [inline pkg/rtc/participant.go:538]: Is it possible to reword this comment and the one below as these probably do not always apply in OSS code. Maybe leave them as PR comments inline rather than in code?

Comment (davidzhao) [reply pkg/rtc/participant.go:538]: I believe it does apply. participants have to be persisted to Redis
