### PR TITLE
Refine ipv6 support

### LINKED ISSUE #4318: Node IP can only be set to 1 value
**Describe the bug**
The `node_ip` config property can only be set to 1 value. In a dual-stack configuration, this means it is not possible to configure one of the two families but it will still advertise it even if not binding to both stacks.

I.o.w.:
If `node_ip` is set to an IPv4 address, the given address will be used for the advertised IPv4 addresses but the advertised IPv6 addresses will be some node local address.  
If `node_ip` is set to an IPv6 address, the given address will be used for the advertised IPv6 addresses but the advertised IPv4 addresses will be some node local address.  

**Server**
- Version: 1.9.11
- Environment: k8s in a dual stack environment

**Client**
N/A

**To Reproduce**
1. Ensure running on a dual stack system. You don't even need to bind to both.
2. Set `use_external_ip: false` to allow the use of `node_ip`.
3. Configure a `node_ip`. Use an address not detectable on the host itself. It does not need to be actually reachable.
5. Connect to LiveKit. You can use the connection tester for this. It does not need to succeed in connecting, it just needs to receive and show you the advertised addresses.
6. Observe the returned addresses in the connection tester.
7. Note that the configured `node_ip` is used for the addresses matching the address family but that the addresses for the other address family end up using some address detected on the node itself.  

**Expected behavior**
1. When `node_ip` is set/configured, no addresses should be returned that aren't explicitly configured.
2. Multiple addresses should be configurable using `node_ip` (a change into `node_ips: []` would be needed).

**Additional context**
Not supporting multiple IPs also means LiveKit can't currently be configured if it is available on multiple addresses and/or address families that are not directly configured on the host itself, nor resolvable by STUN (e.g. when outbound traffic exits over a different IP than where incoming traffic is expected to arrive).  

There is also an underlying problem i.r.t. dual stack systems around the advertisements which results in at least one internal address being exposed publicly at all times. See also #4319

### PR DESCRIPTION
**Pull request by cnderrauber**
Fix #4318 #4319 . See https://github.com/livekit/mediatransportutil/pull/79

### CODE REVIEW

File: pkg/service/turn.go [hunk 1]
```diff
@@ -60,7 +60,7 @@ func NewTurnServer(conf *config.Config, authHandler turn.AuthHandler, standalone
 		LoggerFactory: pionlogger.NewLoggerFactory(logger.GetLogger()),
 	}
 	var relayAddrGen turn.RelayAddressGenerator = &turn.RelayAddressGeneratorPortRange{
-		RelayAddress: net.ParseIP(conf.RTC.NodeIP),
+		RelayAddress: net.ParseIP(conf.RTC.NodeIP.V4),
```
Comment (boks1971) [inline pkg/service/turn.go:66]: Is some earlier bit erroring out if `V4` not set up properly?

Comment (boks1971) [reply pkg/service/turn.go:66]: IOW, can this be started with invalid IP?

Comment (cnderrauber) [reply pkg/service/turn.go:66]: added check in https://github.com/livekit/livekit/pull/4352/commits/e74bf31817af2d209ce9b33ca8ee51df668c445f , it can't be invalid as the nat1to1ips use it also.
